"""EnumTransactionTypes: enum of possible values (BOLETO, CARTAO, CONVENIO_ARRECADACAO, DEPOSITO, DOC, ENCARGOS_JUROS_CHEQUE_ESPECIAL, ...) for this field, per the Accounts OpenAPI spec."""

from enum import Enum


class EnumTransactionTypes(str, Enum):
    BOLETO = "BOLETO"
    CARTAO = "CARTAO"
    CONVENIO_ARRECADACAO = "CONVENIO_ARRECADACAO"
    DEPOSITO = "DEPOSITO"
    DOC = "DOC"
    ENCARGOS_JUROS_CHEQUE_ESPECIAL = "ENCARGOS_JUROS_CHEQUE_ESPECIAL"
    FOLHA_PAGAMENTO = "FOLHA_PAGAMENTO"
    OPERACAO_CREDITO = "OPERACAO_CREDITO"
    OUTROS = "OUTROS"
    PACOTE_TARIFA_SERVICOS = "PACOTE_TARIFA_SERVICOS"
    PIX = "PIX"
    PORTABILIDADE_SALARIO = "PORTABILIDADE_SALARIO"
    RENDIMENTO_APLIC_FINANCEIRA = "RENDIMENTO_APLIC_FINANCEIRA"
    RESGATE_APLIC_FINANCEIRA = "RESGATE_APLIC_FINANCEIRA"
    SAQUE = "SAQUE"
    TARIFA_SERVICOS_AVULSOS = "TARIFA_SERVICOS_AVULSOS"
    TED = "TED"
    TRANSFERENCIA_MESMA_INSTITUICAO = "TRANSFERENCIA_MESMA_INSTITUICAO"

    def __str__(self) -> str:
        return str(self.value)
