"""EnumCreditCardAccountsProductType: enum of possible values (BASICO_INTERNACIONAL, BASICO_NACIONAL, BLACK, BLUE, BLUEBOX, CHEQUE_ELETRONICO, ...) for this field, per the Credit Cards Accounts OpenAPI spec."""

from enum import Enum


class EnumCreditCardAccountsProductType(str, Enum):
    BASICO_INTERNACIONAL = "BASICO_INTERNACIONAL"
    BASICO_NACIONAL = "BASICO_NACIONAL"
    BLACK = "BLACK"
    BLUE = "BLUE"
    BLUEBOX = "BLUEBOX"
    CHEQUE_ELETRONICO = "CHEQUE_ELETRONICO"
    CLASSIC_INTERNACIONAL = "CLASSIC_INTERNACIONAL"
    CLASSIC_NACIONAL = "CLASSIC_NACIONAL"
    COMPRAS = "COMPRAS"
    CORPORATIVO = "CORPORATIVO"
    ELECTRON = "ELECTRON"
    ELETRONIC = "ELETRONIC"
    EMPRESARIAL = "EMPRESARIAL"
    GOLD = "GOLD"
    GRAFITE = "GRAFITE"
    GREEN = "GREEN"
    INFINITE = "INFINITE"
    MAESTRO_MASTERCARD_MAESTRO = "MAESTRO_MASTERCARD_MAESTRO"
    MAIS = "MAIS"
    NANQUIM = "NANQUIM"
    OUTROS = "OUTROS"
    PLATINUM = "PLATINUM"
    PROFISSIONAL_LIBERAL = "PROFISSIONAL_LIBERAL"
    REDESHOP = "REDESHOP"
    STANDARD_INTERNACIONAL = "STANDARD_INTERNACIONAL"
    STANDARD_NACIONAL = "STANDARD_NACIONAL"

    def __str__(self) -> str:
        return str(self.value)
