"""Abstract interface for participating-bank adapters.

Defines the contract that every adapter must implement, following
SOLID principles:
  - Open/Closed: new banks add a subclass without changing existing code.
  - Liskov Substitution: any adapter can be used wherever BankAdapter
    is expected.
  - Interface Segregation: the interface exposes only what the tools need.

Example:
    >>> class MyBankAdapter(BankAdapter):
    ...     @property
    ...     def bank_id(self) -> str:
    ...         return "my_bank"
    ...     async def get_accounts(self, ...) -> AccountList:
    ...         ...
"""

import uuid
from abc import ABC, abstractmethod
from dataclasses import dataclass
from typing import Any

import httpx
import structlog

from openfinance_br_mcp.auth.token import TokenStore
from openfinance_br_mcp.config import settings
from openfinance_br_mcp.schemas.account import AccountBalance, AccountList
from openfinance_br_mcp.schemas.credit_card import Bill, CreditCardAccount
from openfinance_br_mcp.schemas.investment import (
    FundList,
    InvestmentList,
    TreasureTitleList,
    VariableIncomeList,
)
from openfinance_br_mcp.schemas.pix import PixKey, PixPayment, PixPaymentRequest
from openfinance_br_mcp.schemas.transaction import TransactionFilters, TransactionList

log = structlog.get_logger(__name__)


def build_fapi_headers(access_token: str) -> dict[str, str]:
    """Builds the header set required on every FAPI-BR protected resource call.

    The FAPI-BR security profile requires 'x-fapi-interaction-id' on
    every call to a protected resource (accounts, consents, payments,
    etc.) - the authorization server may reject requests missing it,
    and it's the correlation ID used to trace a single request across
    client and bank logs. Previously only 'Authorization' was sent.

    Used by call sites that still issue requests manually via
    ``self._http`` (e.g. ``initiate_pix``'s JWS-signed body, or
    ``list_pix_keys``, a proprietary extension with no generated
    client - see ``DefaultOpenFinanceAdapter``). Call sites that use a
    generated client from ``clients/`` instead use
    ``build_fapi_call_kwargs`` below, since those operation functions
    take ``authorization``/``x_fapi_interaction_id`` as individual
    keyword arguments rather than a headers dict.

    Args:
        access_token: Bearer token for the request.

    Returns:
        Headers dict with 'Authorization' and a freshly generated
        'x-fapi-interaction-id'.
    """
    return {
        "Authorization": f"Bearer {access_token}",
        "x-fapi-interaction-id": str(uuid.uuid4()),
    }


def build_fapi_call_kwargs(access_token: str) -> dict[str, Any]:
    """Builds the FAPI-BR keyword arguments for a generated client operation.

    Every operation function generated by ``openapi-python-client``
    under ``clients/`` (e.g.
    ``clients.accounts_v2_4_2.api.accounts.accounts_get_accounts.asyncio_detailed``)
    declares ``authorization: str`` and ``x_fapi_interaction_id: UUID``
    as required keyword arguments rather than accepting a raw headers
    dict - the generator detected them as always-required parameters
    per the OpenAPI spec, not as an injectable client-level auth
    scheme (see ``clients/<family>/client.py``'s ``AuthenticatedClient``,
    whose own ``token`` field is unused here since this project injects
    its own mTLS-configured ``httpx.AsyncClient`` via
    ``set_async_httpx_client`` and builds the Authorization header per
    call instead). Spread this dict into every generated operation call
    with ``**build_fapi_call_kwargs(token)``.

    Returns a plain ``str`` for ``x_fapi_interaction_id`` even though
    the generated functions type-hint it as ``UUID`` - confirmed by
    direct testing that passing a real ``uuid.UUID`` instance crashes
    at request time (``_get_kwargs`` assigns it straight into an httpx
    headers dict without stringifying it first: 'Header value must be
    str or bytes, not uuid.UUID'). This is a bug in the vendored,
    generated code itself, not something to fix by hand-editing
    ``clients/`` (regenerating would revert it - see
    ``clients/__init__.py``): passing a ``str`` here satisfies both the
    real runtime requirement and mypy, since this dict is spread with
    ``**`` into ``dict[str, Any]``-typed kwargs, which mypy does not
    check key-by-key against the callee's declared parameter types.

    Args:
        access_token: Bearer token for the request.

    Returns:
        Dict with ``authorization`` (prefixed 'Bearer ') and a freshly
        generated ``x_fapi_interaction_id`` (as ``str``).
    """
    return {
        "authorization": f"Bearer {access_token}",
        "x_fapi_interaction_id": str(uuid.uuid4()),
    }


@dataclass(frozen=True)
class BankEndpoints:
    """Per-API-family base URLs for one bank, resolved via the Directory.

    Read-family fields are the bare '/open-banking'-prefixed base URL in
    the same shape ``DirectoryClient.resolve()`` returns as
    ``ResolvedApi.base_url`` (e.g. 'https://host/open-banking'). Payment
    fields are the exact collection endpoints published by the Directory,
    because payments consent and PIX are distinct family registrations and
    their version must not be reconstructed locally.
    ``DefaultOpenFinanceAdapter._client_base_url`` is solely
    responsible for appending those (via ``_FAMILY_VERSIONS``) to
    build the fully-versioned base URL a generated client actually
    needs (e.g. 'https://host/open-banking/accounts/v2') - keeping
    that one place as the single source of truth for which version
    this project targets per family, rather than duplicating version
    strings here too.

    A ``None`` field means the Directory didn't publish (or failed to
    resolve) that family for this bank. Real adapters configured in
    fail-closed mode reject calls to that family; only the explicit
    hardcoded-development fallback may reuse the adapter's default host.

    Attributes:
        accounts: Accounts base URL.
        credit_cards_accounts: Credit Cards Accounts base URL.
        payments_consents: Exact payment-consent collection endpoint.
        payments_pix: Exact PIX-payment collection endpoint.
        consents: Consents base URL.
        bank_fixed_incomes: Bank Fixed Incomes base URL.
        funds: Funds base URL.
        variable_incomes: Variable Incomes base URL.
        treasure_titles: Treasure Titles base URL.
    """

    accounts: str | None = None
    credit_cards_accounts: str | None = None
    payments_consents: str | None = None
    payments_pix: str | None = None
    consents: str | None = None
    bank_fixed_incomes: str | None = None
    funds: str | None = None
    variable_incomes: str | None = None
    treasure_titles: str | None = None

    def get(self, api_family_type: str) -> str | None:
        """Returns the configured URL for a family, if available."""
        value = getattr(self, api_family_type.replace("-", "_"), None)
        return str(value) if value is not None else None

    def get_or(self, api_family_type: str, default: str) -> str:
        """Returns the resolved base URL for a family, or a fallback.

        Args:
            api_family_type: Directory ApiFamilyType, hyphenated as
                published (e.g. 'credit-cards-accounts',
                'bank-fixed-incomes', 'variable-incomes',
                'treasure-titles') - translated to this dataclass's
                underscored field name internally.
            default: Value to return if this family wasn't resolved.

        Returns:
            The family's versioned base URL, or ``default``.
        """
        value = self.get(api_family_type)
        return value if value is not None else default


class BankAdapter(ABC):
    """Contract for integrating with institutions participating in
    Open Finance Brasil.

    Attributes:
        _token_store: Token store shared with the server.
        _http: HTTP client configured with mTLS for this institution.
    """

    def __init__(self, token_store: TokenStore, http_client: httpx.AsyncClient) -> None:
        """Initializes the adapter with injected dependencies.

        Args:
            token_store: Store used to obtain access tokens.
            http_client: HTTP client configured with mTLS for this institution.
        """
        self._token_store = token_store
        self._http = http_client

    @property
    @abstractmethod
    def bank_id(self) -> str:
        """Unique identifier of the bank (e.g. 'nubank', 'sicoob').

        Returns:
            snake_case string identifying the bank.
        """
        ...

    @property
    @abstractmethod
    def base_url(self) -> str:
        """Base URL of this institution's Open Finance APIs.

        Returns:
            Base URL without a trailing slash.
        """
        ...

    @property
    @abstractmethod
    def token_endpoint(self) -> str:
        """URL of the /token endpoint used to refresh tokens.

        Returns:
            Full URL of the token endpoint.
        """
        ...

    async def aclose(self) -> None:
        """Releases any resources this adapter owns beyond ``self._http``.

        No-op by default (e.g. ``MockOpenFinanceAdapter`` owns
        nothing). ``DefaultOpenFinanceAdapter`` overrides this to close
        the per-API-family generated clients it lazily builds and
        caches (each with its own internal ``httpx.AsyncClient`` - see
        ``default_adapter.py::_generated_client``), since those are
        separate from the shared ``self._http`` the caller (see
        ``context.py::app_lifespan``) already closes itself.
        """
        return

    @abstractmethod
    async def get_accounts(self, subject_id: str) -> AccountList:
        """Lists all of the user's accounts at this institution.

        Args:
            subject_id: Identifier of the authenticated user.

        Returns:
            Paginated list of accounts.
        """
        ...

    @abstractmethod
    async def get_balance(self, subject_id: str, account_id: str) -> AccountBalance:
        """Returns the balance of a specific account.

        Args:
            subject_id: Identifier of the user.
            account_id: Account ID.

        Returns:
            Current balance of the account.
        """
        ...

    @abstractmethod
    async def list_transactions(
        self,
        subject_id: str,
        filters: TransactionFilters,
    ) -> TransactionList:
        """Returns the statement of an account with optional filters.

        Args:
            subject_id: Identifier of the user.
            filters: Date, type, and pagination filters.

        Returns:
            Paginated list of transactions.
        """
        ...

    @abstractmethod
    async def get_credit_card_accounts(
        self, subject_id: str
    ) -> list[CreditCardAccount]:
        """Lists the user's credit card accounts.

        Args:
            subject_id: Identifier of the user.

        Returns:
            List of credit card accounts.
        """
        ...

    @abstractmethod
    async def get_credit_card_bills(
        self, subject_id: str, credit_card_account_id: str
    ) -> list[Bill]:
        """Returns the bills of a credit card.

        Args:
            subject_id: Identifier of the user.
            credit_card_account_id: ID of the credit card account.

        Returns:
            List of bills.
        """
        ...

    @abstractmethod
    async def list_pix_keys(self, subject_id: str, account_id: str) -> list[PixKey]:
        """Lists PIX keys linked to an account.

        Args:
            subject_id: Identifier of the user.
            account_id: Account ID.

        Returns:
            List of registered PIX keys.
        """
        ...

    @abstractmethod
    async def initiate_pix(
        self, subject_id: str, request: PixPaymentRequest
    ) -> PixPayment:
        """Initiates a PIX payment.

        Args:
            subject_id: Identifier of the paying user.
            request: Payment data with an idempotency_key.

        Returns:
            Result of the payment initiation.
        """
        ...

    @abstractmethod
    async def list_investments(self, subject_id: str) -> InvestmentList:
        """Lists the user's fixed-income investments.

        Args:
            subject_id: Identifier of the user.

        Returns:
            List of investments.
        """
        ...

    @abstractmethod
    async def list_funds(self, subject_id: str) -> FundList:
        """Lists the user's investment fund positions (P1.3).

        Args:
            subject_id: Identifier of the user.

        Returns:
            List of investment funds.
        """
        ...

    @abstractmethod
    async def list_variable_incomes(self, subject_id: str) -> VariableIncomeList:
        """Lists the user's variable income asset positions (P1.3):
        stocks, ETFs, and other exchange-traded assets.

        Args:
            subject_id: Identifier of the user.

        Returns:
            List of variable income assets.
        """
        ...

    @abstractmethod
    async def list_treasure_titles(self, subject_id: str) -> TreasureTitleList:
        """Lists the user's treasury bond (Tesouro Direto) positions (P1.3).

        Args:
            subject_id: Identifier of the user.

        Returns:
            List of treasury bonds.
        """
        ...

    async def _get_token(self, subject_id: str, *, purpose: str = "data") -> str:
        """Obtains a valid access token for the subject.

        Delegates to the TokenStore, which refreshes automatically
        if needed.

        Args:
            subject_id: Identifier of the user.
            purpose: 'data' (default) or 'payment' - see
                ``auth/token.py``'s composite key. A payment-bound
                token (obtained via the Payments API's own consent
                flow, see auth/payment_consent.py and
                tools/payments.py) is never the same token as a
                data-sharing consent's - passing the wrong purpose
                here would either fail to find a token at all or, far
                worse, silently reuse a data-sharing token to
                authorize a payment.

        Returns:
            Access token as a string.
        """
        token = await self._token_store.get_valid_token(
            self.bank_id,
            subject_id,
            self._http,
            self.token_endpoint,
            purpose=purpose,
        )
        return token.access_token

    def _build_http_client(self) -> httpx.AsyncClient:
        """Builds an HTTP client configured with mTLS for this institution.

        Returns:
            AsyncClient ready to use, with timeout and mTLS configured.
        """
        kwargs: dict[str, Any] = {
            "timeout": settings.http_timeout_seconds,
            "http2": True,
        }

        if settings.mtls_enabled:
            kwargs["cert"] = (settings.mtls_cert_path, settings.mtls_key_path)

        return httpx.AsyncClient(**kwargs)
