"""EnumErrorsCreatePayment: enum of possible values (COBRANCA_INVALIDA, CONSENTIMENTO_INVALIDO, CONSENTIMENTO_PENDENTE_AUTORIZACAO, DETALHE_PAGAMENTO_INVALIDO, ERRO_IDEMPOTENCIA, NAO_INFORMADO, ...) for this field, per the Payments OpenAPI spec."""

from enum import Enum


class EnumErrorsCreatePayment(str, Enum):
    COBRANCA_INVALIDA = "COBRANCA_INVALIDA"
    CONSENTIMENTO_INVALIDO = "CONSENTIMENTO_INVALIDO"
    CONSENTIMENTO_PENDENTE_AUTORIZACAO = "CONSENTIMENTO_PENDENTE_AUTORIZACAO"
    DETALHE_PAGAMENTO_INVALIDO = "DETALHE_PAGAMENTO_INVALIDO"
    ERRO_IDEMPOTENCIA = "ERRO_IDEMPOTENCIA"
    NAO_INFORMADO = "NAO_INFORMADO"
    PAGAMENTO_DIVERGENTE_CONSENTIMENTO = "PAGAMENTO_DIVERGENTE_CONSENTIMENTO"
    PAGAMENTO_RECUSADO_DETENTORA = "PAGAMENTO_RECUSADO_DETENTORA"
    PAGAMENTO_RECUSADO_SPI = "PAGAMENTO_RECUSADO_SPI"
    PARAMETRO_INVALIDO = "PARAMETRO_INVALIDO"
    PARAMETRO_NAO_INFORMADO = "PARAMETRO_NAO_INFORMADO"
    SALDO_INSUFICIENTE = "SALDO_INSUFICIENTE"
    VALOR_ACIMA_LIMITE = "VALOR_ACIMA_LIMITE"
    VALOR_INVALIDO = "VALOR_INVALIDO"

    def __str__(self) -> str:
        return str(self.value)
