"""EnumConsentRejectionReasonType: enum of possible values (CONTAS_ORIGEM_DESTINO_IGUAIS, CONTA_NAO_PERMITE_PAGAMENTO, FALHA_INFRAESTRUTURA, NAO_INFORMADO, QRCODE_INVALIDO, REJEITADO_USUARIO, ...) for this field, per the Payments OpenAPI spec."""

from enum import Enum


class EnumConsentRejectionReasonType(str, Enum):
    CONTAS_ORIGEM_DESTINO_IGUAIS = "CONTAS_ORIGEM_DESTINO_IGUAIS"
    CONTA_NAO_PERMITE_PAGAMENTO = "CONTA_NAO_PERMITE_PAGAMENTO"
    FALHA_INFRAESTRUTURA = "FALHA_INFRAESTRUTURA"
    NAO_INFORMADO = "NAO_INFORMADO"
    QRCODE_INVALIDO = "QRCODE_INVALIDO"
    REJEITADO_USUARIO = "REJEITADO_USUARIO"
    SALDO_INSUFICIENTE = "SALDO_INSUFICIENTE"
    TEMPO_EXPIRADO_AUTORIZACAO = "TEMPO_EXPIRADO_AUTORIZACAO"
    TEMPO_EXPIRADO_CONSUMO = "TEMPO_EXPIRADO_CONSUMO"
    VALOR_ACIMA_LIMITE = "VALOR_ACIMA_LIMITE"
    VALOR_INVALIDO = "VALOR_INVALIDO"

    def __str__(self) -> str:
        return str(self.value)
