"""EnumRejectionReasonTypeGetPix: enum of possible values (COBRANCA_INVALIDA, CONTAS_ORIGEM_DESTINO_IGUAIS, DETALHE_PAGAMENTO_INVALIDO, FALHA_AGENDAMENTO_PAGAMENTOS, FALHA_INFRAESTRUTURA, FALHA_INFRAESTRUTURA_DETENTORA, ...) for this field, per the Payments OpenAPI spec."""

from enum import Enum


class EnumRejectionReasonTypeGetPix(str, Enum):
    COBRANCA_INVALIDA = "COBRANCA_INVALIDA"
    CONTAS_ORIGEM_DESTINO_IGUAIS = "CONTAS_ORIGEM_DESTINO_IGUAIS"
    DETALHE_PAGAMENTO_INVALIDO = "DETALHE_PAGAMENTO_INVALIDO"
    FALHA_AGENDAMENTO_PAGAMENTOS = "FALHA_AGENDAMENTO_PAGAMENTOS"
    FALHA_INFRAESTRUTURA = "FALHA_INFRAESTRUTURA"
    FALHA_INFRAESTRUTURA_DETENTORA = "FALHA_INFRAESTRUTURA_DETENTORA"
    FALHA_INFRAESTRUTURA_DICT = "FALHA_INFRAESTRUTURA_DICT"
    FALHA_INFRAESTRUTURA_ICP = "FALHA_INFRAESTRUTURA_ICP"
    FALHA_INFRAESTRUTURA_PSP_RECEBEDOR = "FALHA_INFRAESTRUTURA_PSP_RECEBEDOR"
    FALHA_INFRAESTRUTURA_SPI = "FALHA_INFRAESTRUTURA_SPI"
    NAO_INFORMADO = "NAO_INFORMADO"
    PAGAMENTO_DIVERGENTE_CONSENTIMENTO = "PAGAMENTO_DIVERGENTE_CONSENTIMENTO"
    PAGAMENTO_RECUSADO_DETENTORA = "PAGAMENTO_RECUSADO_DETENTORA"
    PAGAMENTO_RECUSADO_SPI = "PAGAMENTO_RECUSADO_SPI"
    SALDO_INSUFICIENTE = "SALDO_INSUFICIENTE"
    VALOR_ACIMA_LIMITE = "VALOR_ACIMA_LIMITE"
    VALOR_INVALIDO = "VALOR_INVALIDO"

    def __str__(self) -> str:
        return str(self.value)
