"""ResponseConsentDataPermissionsItem: a data model of the Consents API (Open Finance Brasil), per the OpenAPI spec's schema for it."""

from enum import Enum


class ResponseConsentDataPermissionsItem(str, Enum):
    ACCOUNTS_BALANCES_READ = "ACCOUNTS_BALANCES_READ"
    ACCOUNTS_OVERDRAFT_LIMITS_READ = "ACCOUNTS_OVERDRAFT_LIMITS_READ"
    ACCOUNTS_READ = "ACCOUNTS_READ"
    ACCOUNTS_TRANSACTIONS_READ = "ACCOUNTS_TRANSACTIONS_READ"
    BANK_FIXED_INCOMES_READ = "BANK_FIXED_INCOMES_READ"
    CREDIT_CARDS_ACCOUNTS_BILLS_READ = "CREDIT_CARDS_ACCOUNTS_BILLS_READ"
    CREDIT_CARDS_ACCOUNTS_BILLS_TRANSACTIONS_READ = (
        "CREDIT_CARDS_ACCOUNTS_BILLS_TRANSACTIONS_READ"
    )
    CREDIT_CARDS_ACCOUNTS_LIMITS_READ = "CREDIT_CARDS_ACCOUNTS_LIMITS_READ"
    CREDIT_CARDS_ACCOUNTS_READ = "CREDIT_CARDS_ACCOUNTS_READ"
    CREDIT_CARDS_ACCOUNTS_TRANSACTIONS_READ = "CREDIT_CARDS_ACCOUNTS_TRANSACTIONS_READ"
    CREDIT_FIXED_INCOMES_READ = "CREDIT_FIXED_INCOMES_READ"
    CUSTOMERS_BUSINESS_ADITTIONALINFO_READ = "CUSTOMERS_BUSINESS_ADITTIONALINFO_READ"
    CUSTOMERS_BUSINESS_IDENTIFICATIONS_READ = "CUSTOMERS_BUSINESS_IDENTIFICATIONS_READ"
    CUSTOMERS_PERSONAL_ADITTIONALINFO_READ = "CUSTOMERS_PERSONAL_ADITTIONALINFO_READ"
    CUSTOMERS_PERSONAL_IDENTIFICATIONS_READ = "CUSTOMERS_PERSONAL_IDENTIFICATIONS_READ"
    EXCHANGES_READ = "EXCHANGES_READ"
    FINANCINGS_PAYMENTS_READ = "FINANCINGS_PAYMENTS_READ"
    FINANCINGS_READ = "FINANCINGS_READ"
    FINANCINGS_SCHEDULED_INSTALMENTS_READ = "FINANCINGS_SCHEDULED_INSTALMENTS_READ"
    FINANCINGS_WARRANTIES_READ = "FINANCINGS_WARRANTIES_READ"
    FUNDS_READ = "FUNDS_READ"
    INVOICE_FINANCINGS_PAYMENTS_READ = "INVOICE_FINANCINGS_PAYMENTS_READ"
    INVOICE_FINANCINGS_READ = "INVOICE_FINANCINGS_READ"
    INVOICE_FINANCINGS_SCHEDULED_INSTALMENTS_READ = (
        "INVOICE_FINANCINGS_SCHEDULED_INSTALMENTS_READ"
    )
    INVOICE_FINANCINGS_WARRANTIES_READ = "INVOICE_FINANCINGS_WARRANTIES_READ"
    LOANS_PAYMENTS_READ = "LOANS_PAYMENTS_READ"
    LOANS_READ = "LOANS_READ"
    LOANS_SCHEDULED_INSTALMENTS_READ = "LOANS_SCHEDULED_INSTALMENTS_READ"
    LOANS_WARRANTIES_READ = "LOANS_WARRANTIES_READ"
    RESOURCES_READ = "RESOURCES_READ"
    TREASURE_TITLES_READ = "TREASURE_TITLES_READ"
    UNARRANGED_ACCOUNTS_OVERDRAFT_PAYMENTS_READ = (
        "UNARRANGED_ACCOUNTS_OVERDRAFT_PAYMENTS_READ"
    )
    UNARRANGED_ACCOUNTS_OVERDRAFT_READ = "UNARRANGED_ACCOUNTS_OVERDRAFT_READ"
    UNARRANGED_ACCOUNTS_OVERDRAFT_SCHEDULED_INSTALMENTS_READ = (
        "UNARRANGED_ACCOUNTS_OVERDRAFT_SCHEDULED_INSTALMENTS_READ"
    )
    UNARRANGED_ACCOUNTS_OVERDRAFT_WARRANTIES_READ = (
        "UNARRANGED_ACCOUNTS_OVERDRAFT_WARRANTIES_READ"
    )
    VARIABLE_INCOMES_READ = "VARIABLE_INCOMES_READ"

    def __str__(self) -> str:
        return str(self.value)
